# Generated by Django 2.1.4 on 2018-12-18 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_customuser_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии к контактам'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mchs_phone_numb',
            field=models.CharField(max_length=100, verbose_name='тел. номер МЧС'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='regions.Region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sity_phone_numb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='тел. номер город. (с кодом)'),
        ),
    ]
