# Generated by Django 2.1.4 on 2018-12-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20181218_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mchs_phone_numb',
            field=models.CharField(max_length=100, verbose_name='тел. номер МЧС'),
        ),
    ]
