# Generated by Django 2.0.3 on 2018-03-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HazardousChemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('form', models.CharField(max_length=255, null=True)),
                ('gas_density', models.FloatField(blank=True, null=True)),
                ('liquid_density', models.FloatField(blank=True, null=True)),
                ('boiling_t', models.FloatField(blank=True, null=True)),
                ('toxodeth', models.FloatField(blank=True, null=True)),
                ('k1', models.FloatField(blank=True, null=True)),
                ('k2', models.FloatField(blank=True, null=True)),
                ('k3', models.FloatField(blank=True, null=True)),
                ('k7_1', models.CharField(blank=True, max_length=255, null=True)),
                ('k7_1_f', models.CharField(blank=True, max_length=255, null=True)),
                ('k7_2', models.CharField(blank=True, max_length=255, null=True)),
                ('k7_2_f', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Коэффициеты',
                'db_table': 'HazardousChemicals',
                'verbose_name': 'Коэффициеты',
            },
        ),
    ]
