# Generated by Django 2.0.3 on 2018-07-13 10:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HazardousChemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('form', models.CharField(max_length=255, null=True)),
                ('gas_density', models.FloatField(blank=True, null=True)),
                ('liquid_density', models.FloatField(blank=True, null=True)),
                ('boiling_t', models.FloatField(blank=True, null=True)),
                ('toxodeth', models.FloatField(blank=True, null=True)),
                ('k1', models.FloatField(blank=True, null=True)),
                ('k2', models.FloatField(blank=True, null=True)),
                ('k3', models.FloatField(blank=True, null=True)),
                ('k7', django.contrib.postgres.fields.jsonb.JSONField(default='[[0,0,0,0,0], [0,0,0,0,0]]')),
            ],
            options={
                'verbose_name': 'Коэффициеты',
                'verbose_name_plural': 'Коэффициеты',
                'db_table': 'HazardousChemicals',
            },
        ),
    ]
