# Generated by Django 2.0.3 on 2018-07-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazard_substance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardouschemical',
            name='descr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
