# Generated by Django 2.1.4 on 2018-12-22 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0007_auto_20181218_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=150)),
                ('water_type', models.PositiveSmallIntegerField(choices=[(1, 'р.'), (2, 'о.'), (3, 'вдх.'), (4, 'пруд'), (5, 'затон'), (6, 'старица'), (7, 'карьер')], default=1, verbose_name='Тип водоема')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water', to='regions.Region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Водоемы',
                'verbose_name_plural': 'Водоемы',
                'db_table': 'water_bodies',
            },
        ),
    ]
