# Generated by Django 2.1.4 on 2018-12-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_check', '0004_auto_20181223_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='icethickness',
            name='check_date',
            field=models.DateTimeField(null=True),
        ),
    ]
