# Generated by Django 2.1.4 on 2018-12-24 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ice_check', '0005_icethickness_check_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icethickness',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='icethickness',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='icethickness',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='icethickness',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='icethickness',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='icethickness',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ice_thickness', to=settings.AUTH_USER_MODEL),
        ),
    ]
