# Generated by Django 2.1.4 on 2018-12-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_check', '0006_auto_20181224_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icethickness',
            name='check_date',
            field=models.DateField(null=True, verbose_name='Дата измерения'),
        ),
        migrations.AlterField(
            model_name='icethickness',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Описание'),
        ),
    ]
