# Generated by Django 2.1.4 on 2018-12-24 14:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ice_check', '0009_auto_20181224_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecheckpost',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='icethickness',
            name='ice_check_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ice_thickneses', to='ice_check.IceCheckPost', verbose_name='Пункт измерения'),
        ),
        migrations.AlterField(
            model_name='waterbody',
            name='water_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'река'), (2, 'озеро'), (3, 'вдх.'), (4, 'пруд'), (5, 'затон'), (6, 'залив'), (7, 'старица'), (8, 'карьер')], default=1, verbose_name='Тип водоема'),
        ),
    ]
