# Generated by Django 2.1.4 on 2019-01-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_check', '0010_auto_20181224_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecheckpost',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
    ]
