# Generated by Django 2.0.3 on 2018-03-21 14:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Свойства объектов',
                'verbose_name': 'Свойство объекта',
                'db_table': 'objects_features',
            },
        ),
        migrations.CreateModel(
            name='FeatureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descr', models.TextField(blank=True, max_length=500)),
                ('unit_measure', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Свойства типов объектов',
                'verbose_name': 'Свойство типа объекта',
                'db_table': 'objects_types_features',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Объект')),
                ('address', models.CharField(max_length=400, verbose_name='Адрес')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Координаты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('contacts', models.CharField(max_length=600, verbose_name='Контактные данные')),
            ],
            options={
                'verbose_name_plural': 'Объекты',
                'verbose_name': 'Объект',
                'db_table': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descr', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Типы объектов',
                'verbose_name': 'Тип объектов',
                'db_table': 'objects_types',
            },
        ),
        migrations.AddField(
            model_name='object',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geobjects.ObjectType'),
        ),
        migrations.AddField(
            model_name='featuretype',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geobjects.ObjectType'),
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geobjects.FeatureType'),
        ),
        migrations.AddField(
            model_name='feature',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='geobjects.Object'),
        ),
    ]
