# Generated by Django 2.0.3 on 2018-07-13 10:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hazard_substance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='значение')),
            ],
            options={
                'verbose_name': 'Свойство объекта',
                'verbose_name_plural': 'Свойства объекта',
                'db_table': 'objects_features',
            },
        ),
        migrations.CreateModel(
            name='FeatureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('descr', models.TextField(blank=True, max_length=500, verbose_name='описание')),
                ('unit_measure', models.CharField(blank=True, max_length=50, verbose_name='единица измерения')),
                ('ident_name', models.CharField(blank=True, max_length=50, verbose_name='идентификационное имя')),
            ],
            options={
                'verbose_name': 'Свойство типа объекта',
                'verbose_name_plural': 'Свойства типов объектов',
                'db_table': 'objects_types_features',
            },
        ),
        migrations.CreateModel(
            name='Flood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ob', models.IntegerField()),
                ('river', models.CharField(max_length=100)),
                ('riv_sys', models.CharField(max_length=100)),
                ('riv_in_sys', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название объекта')),
                ('address', models.CharField(max_length=400, verbose_name='Адрес')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Координаты (вычисляются)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('contacts', models.TextField(blank=True, default='', max_length=600, verbose_name='Контактные данные')),
                ('district', models.CharField(blank=True, choices=[('ЦАО', 'ЦАО'), ('САО', 'САО'), ('СВАО', 'СВАО'), ('ВАО', 'ВАО'), ('ЮВАО', 'ЮВАО'), ('ЮАО', 'ЮАО'), ('ЮЗАО', 'ЮЗАО'), ('ЗАО', 'ЗАО'), ('СЗАО', 'СЗАО'), ('ЗелАО', 'ЗелАО'), ('НАО', 'НАО'), ('ТАО', 'ТАО'), ('', 'вычисляется')], default='', max_length=15, verbose_name='Округ')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'db_table': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descr', models.TextField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Тип объектов',
                'verbose_name_plural': 'Типы объектов',
                'db_table': 'objects_types',
            },
        ),
        migrations.CreateModel(
            name='SubstanceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_for', models.CharField(blank=True, choices=[('full', 'всех емкостей'), ('one_tank', 'одной емкости')], default='full', max_length=20, verbose_name='Количество для')),
                ('substance_amount', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Количество вещества (т)')),
                ('hc_storage', models.CharField(choices=[('liquid', 'жидкость'), ('gas_no_pressure', 'газ'), ('gas_under_pressure', 'газ под давлением')], default='liquid', max_length=20, verbose_name='Хранение АХОВ')),
                ('embank_height', models.FloatField(blank=True, default=0, verbose_name='Dысота поддона или обваловки (м)')),
                ('hazard_substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hazard_substance.HazardousChemical', verbose_name='Опасное вещество на объекте')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geobjects.Object')),
            ],
            options={
                'verbose_name': 'Количество вещества',
                'verbose_name_plural': 'Количество вещества',
                'db_table': 'substance_amounts',
            },
        ),
        migrations.AddField(
            model_name='object',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geobjects.ObjectType', verbose_name='Тип объекта'),
        ),
        migrations.AddField(
            model_name='featuretype',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geobjects.ObjectType'),
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geobjects.FeatureType', verbose_name='свойство типа'),
        ),
        migrations.AddField(
            model_name='feature',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='geobjects.Object'),
        ),
    ]
