# Generated by Django 2.0.3 on 2018-03-11 22:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geobjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuretype',
            options={'verbose_name': 'Свойство объекта', 'verbose_name_plural': 'Свойства объектов'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterModelOptions(
            name='objecttype',
            options={'verbose_name': 'Тип объектов', 'verbose_name_plural': 'Типы объектов'},
        ),
        migrations.AlterField(
            model_name='object',
            name='address',
            field=models.CharField(max_length=400, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='object',
            name='contacts',
            field=models.CharField(max_length=600, verbose_name='Контактные данные'),
        ),
        migrations.AlterField(
            model_name='object',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Объект'),
        ),
    ]
