# Generated by Django 2.0.3 on 2018-03-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geobjects', '0002_object_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='contacts',
            field=models.TextField(blank=True, default='', max_length=600, verbose_name='Контактные данные'),
        ),
    ]
