# Generated by Django 2.0.3 on 2018-03-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geobjects', '0003_auto_20180321_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objecttype',
            name='descr',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
