# Generated by Django 2.0.3 on 2018-03-21 21:25

from django.db import migrations, models
import geobjects.models


class Migration(migrations.Migration):

    dependencies = [
        ('geobjects', '0004_auto_20180321_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='district',
            field=models.CharField(blank=True,
                                   choices=[('ЦАО', 'ЦАО'), ('САО', 'САО'), ('СВАО', 'СВАО'), ('ВАО', 'ВАО'),
                                            ('ЮВАО', 'ЮВАО'), ('ЮАО', 'ЮАО'), ('ЮЗАО', 'ЮЗАО'), ('ЗАО', 'ЗАО'),
                                            ('CЗАО', 'CЗАО'), ('ЗелАО', 'ЗелАО'), ('НАО', 'НАО'), ('ТАО', 'ТАО'),
                                            ('', 'вычисляется')], default='', max_length=8, verbose_name='Округ'),
        ),
    ]
