# Generated by Django 2.0.3 on 2018-03-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geobjects', '0005_auto_20180321_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='district',
            field=models.CharField(blank=True, choices=[('ЦАО', 'ЦАО'), ('САО', 'САО'), ('СВАО', 'СВАО'), ('ВАО', 'ВАО'), ('ЮВАО', 'ЮВАО'), ('ЮАО', 'ЮАО'), ('ЮЗАО', 'ЮЗАО'), ('ЗАО', 'ЗАО'), ('СЗАО', 'СЗАО'), ('ЗелАО', 'ЗелАО'), ('НАО', 'НАО'), ('ТАО', 'ТАО'), ('', 'вычисляется')], default='', max_length=15, verbose_name='Округ'),
        ),
    ]
