# Generated by Django 2.0.3 on 2018-03-21 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geobjects', '0006_auto_20180321_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Свойство объекта', 'verbose_name_plural': 'Свойства объекта'},
        ),
        migrations.AddField(
            model_name='featuretype',
            name='ident_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='идентификационное имя'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geobjects.FeatureType', verbose_name='свойство типа'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='value',
            field=models.CharField(max_length=200, verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='featuretype',
            name='descr',
            field=models.TextField(blank=True, max_length=500, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='featuretype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='featuretype',
            name='unit_measure',
            field=models.CharField(blank=True, max_length=50, verbose_name='единица измерения'),
        ),
    ]
