# Generated by Django 2.0.3 on 2018-03-29 11:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geobjects', '0008_auto_20180329_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ob', models.IntegerField()),
                ('river', models.CharField(max_length=100)),
                ('riv_sys', models.CharField(max_length=100)),
                ('riv_in_sys', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
