# Generated by Django 2.0.3 on 2018-03-30 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hazard_substance', '0001_initial'),
        ('geobjects', '0009_flood'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstanceAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance_amount', models.IntegerField(blank=True, default=0, verbose_name='Общее количество вещества (т)')),
                ('tank_substance_amount', models.IntegerField(blank=True, default=0, verbose_name='Количество вещества в 1 емкости (т)')),
                ('hazard_substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hazard_substance.HazardousChemical', verbose_name='Опасное вещество на объекте')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substance_amounts', to='geobjects.Object')),
            ],
            options={
                'db_table': 'substance_amounts',
                'verbose_name': 'Количество вещества',
                'verbose_name_plural': 'Количество вещества',
            },
        ),
    ]
