# Generated by Django 2.0.3 on 2018-03-30 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geobjects', '0010_substanceamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substanceamount',
            old_name='substance_amount',
            new_name='full_substance_amount',
        ),
    ]
