# Generated by Django 2.0.3 on 2018-03-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geobjects', '0011_auto_20180330_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substanceamount',
            name='full_substance_amount',
        ),
        migrations.RemoveField(
            model_name='substanceamount',
            name='tank_substance_amount',
        ),
        migrations.AddField(
            model_name='substanceamount',
            name='AMOUNT_FOR',
            field=models.CharField(blank=True, choices=[('full', 'для всех емкостей'), ('one_tank', 'одной емкости')], default='full', max_length=20, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='substanceamount',
            name='hc_storage',
            field=models.CharField(choices=[('liquid', 'жидкость'), ('gas', 'газ')], default='liquid', max_length=8, verbose_name='Хранение АХОВ'),
        ),
        migrations.AddField(
            model_name='substanceamount',
            name='substance_amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество вещества (т)'),
        ),
    ]
