# Generated by Django 2.0.3 on 2018-03-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geobjects', '0012_auto_20180331_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substanceamount',
            name='AMOUNT_FOR',
        ),
        migrations.AddField(
            model_name='substanceamount',
            name='amount_for',
            field=models.CharField(blank=True, choices=[('full', 'всех емкостей'), ('one_tank', 'одной емкости')], default='full', max_length=20, verbose_name='Количество для'),
        ),
    ]
