# Generated by Django 2.0.3 on 2018-03-31 14:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geobjects', '0013_auto_20180331_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Координаты (вычисляются)'),
        ),
    ]
