# Generated by Django 2.0.3 on 2018-04-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geobjects', '0014_auto_20180331_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='substanceamount',
            name='embank_height',
            field=models.FloatField(blank=True, default=0, verbose_name='Dысота поддона или обваловки (м)'),
        ),
        migrations.AlterField(
            model_name='substanceamount',
            name='hc_storage',
            field=models.CharField(choices=[('liquid', 'жидкость'), ('gas_no_pressure', 'газ'), ('gas_under_pressure', 'газ под давлением')], default='liquid', max_length=8, verbose_name='Хранение АХОВ'),
        ),
    ]
