# Generated by Django 2.0.3 on 2018-04-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geobjects', '0015_auto_20180402_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substanceamount',
            name='hc_storage',
            field=models.CharField(choices=[('liquid', 'жидкость'), ('gas_no_pressure', 'газ'), ('gas_under_pressure', 'газ под давлением')], default='liquid', max_length=20, verbose_name='Хранение АХОВ'),
        ),
        migrations.AlterField(
            model_name='substanceamount',
            name='substance_amount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Количество вещества (т)'),
        ),
    ]
