# Generated by Django 2.0.3 on 2018-03-21 14:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geobjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rd90Calc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(default='Moscow', max_length=50, verbose_name='Название города')),
                ('time_of_day', models.CharField(blank=True, choices=[('morning', 'утро'), ('day', 'день'), ('evening', 'вечер'), ('night', 'ночь'), ('', 'вычисляется')], default='', max_length=50, verbose_name='Время суток')),
                ('crash_dtime', models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 21, 14, 17, 58, 254903, tzinfo=utc), null=True, verbose_name='Время аварии')),
                ('minutes_after_crach', models.IntegerField(blank=True, null=True, verbose_name='Количество минут после аварии')),
                ('wind_speed', models.IntegerField(verbose_name='Скорость ветра (м/с)')),
                ('air_t', models.IntegerField(verbose_name='Температура воздуха (C)')),
                ('chemicals_amount', models.IntegerField(verbose_name='Количество вещества (т)')),
                ('dovsoa', models.CharField(blank=True, choices=[('из', 'изотермия'), ('ин', 'инверсия'), ('к', 'конверсия'), ('', 'вычисляется')], default='', max_length=10, verbose_name='Cтепень вертикальной устойчивости воздуха')),
                ('hc_storage', models.CharField(choices=[('liquid', 'жидкость'), ('gas', 'газ')], default='gas', max_length=8, verbose_name='АХОВ')),
                ('chem_danger_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geobjects.Object', verbose_name='ХОО')),
                ('chemical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazard_substance.HazardousChemical', verbose_name='АХОВ')),
            ],
            options={
                'verbose_name_plural': 'РД 90 расчеты',
                'verbose_name': 'РД 90 расчет',
                'db_table': 'rd90calcs',
            },
        ),
    ]
