# Generated by Django 2.0.3 on 2018-07-13 10:15

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weather', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geobjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rd90Calc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crash_dtime', models.DateTimeField(blank=True, null=True, verbose_name='Время аварии')),
                ('after_crash_time', models.DurationField(blank=True, default=datetime.timedelta(0, 3600), null=True, verbose_name='Количество минут после аварии')),
                ('evaporation_duration', models.DurationField(blank=True, editable=False, null=True, verbose_name='Продолжительность испарения вещества')),
                ('full_contamination_depth', models.FloatField(blank=True, default=0, editable=False, max_length=500.0, verbose_name='Полная глубина зоны заражения Г (км)')),
                ('angular_size', models.PositiveSmallIntegerField(blank=True, default=0, editable=False, verbose_name='Значение углового размера зоны заражения (град)')),
                ('possible_contamination_area', models.FloatField(blank=True, default=0, editable=False, verbose_name='Площадь зоны возможного заражения АХОВ (квадр. км)')),
                ('actual_contamination_area', models.FloatField(blank=True, default=0, editable=False, verbose_name='Площадь зоны фактического заражения АХОВ (квадр. км)')),
                ('json_calculation', django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True)),
                ('chem_danger_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geobjects.Object', verbose_name='ХОО')),
                ('chemical', models.ManyToManyField(to='geobjects.SubstanceInfo', verbose_name='Количество вещества')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rd90calcs', to=settings.AUTH_USER_MODEL)),
                ('weather', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.Weather', verbose_name='Погодные условия')),
            ],
            options={
                'verbose_name': 'РД 90 расчет',
                'verbose_name_plural': 'РД 90 расчеты',
                'db_table': 'rd90calcs',
            },
        ),
    ]
