# Generated by Django 2.0.3 on 2018-03-21 14:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rd90', '0002_auto_20180321_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rd90calc',
            name='crash_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 21, 14, 40, 44, 771849, tzinfo=utc), null=True, verbose_name='Время аварии'),
        ),
    ]
