# Generated by Django 2.0.3 on 2018-03-21 21:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rd90', '0007_auto_20180321_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rd90calc',
            name='crash_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 21, 21, 25, 50, 973886, tzinfo=utc), null=True, verbose_name='Время аварии'),
        ),
    ]
