# Generated by Django 2.0.3 on 2018-03-21 22:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rd90', '0009_auto_20180321_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rd90calc',
            name='crash_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 21, 22, 8, 6, 722715, tzinfo=utc), null=True, verbose_name='Время аварии'),
        ),
    ]
