# Generated by Django 2.0.3 on 2018-03-29 09:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rd90', '0012_auto_20180321_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rd90calc',
            name='chemical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazard_substance.HazardousChemical', verbose_name='АХОВ'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='chemicals_amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество вещества (т)'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='crash_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 29, 9, 2, 30, 67737, tzinfo=utc), null=True, verbose_name='Время аварии'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='hc_storage',
            field=models.CharField(choices=[('liquid', 'жидкость'), ('gas', 'газ')], default='gas', max_length=8, verbose_name='Хранение АХОВ'),
        ),

    ]
