# Generated by Django 2.0.3 on 2018-03-30 02:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rd90', '0015_auto_20180329_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rd90calc',
            name='crash_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 30, 2, 37, 20, 678240, tzinfo=utc), null=True, verbose_name='Время аварии'),
        ),
    ]
