# Generated by Django 2.0.3 on 2018-03-30 03:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rd90', '0016_auto_20180330_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rd90calc',
            name='chemical',
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='chemicals_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geobjects.SubstanceAmount', verbose_name='Количество вещества (т)'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='crash_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 30, 3, 5, 17, 950208, tzinfo=utc), null=True, verbose_name='Время аварии'),
        ),
    ]
