# Generated by Django 2.0.3 on 2018-03-30 03:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rd90', '0017_auto_20180330_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rd90calc',
            name='crash_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 30, 3, 19, 26, 734845, tzinfo=utc), null=True, verbose_name='Время аварии'),
        ),
    ]
