# Generated by Django 2.0.3 on 2018-03-30 03:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rd90', '0018_auto_20180330_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='rd90calc',
            name='chemicals_amount_calc',
            field=models.CharField(choices=[('tank_substance_amount', 'для одной емкости'), ('full_substance_amount', 'для всего количества')], default='full_substance_amount', max_length=30, verbose_name='Расчет для:'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='crash_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 30, 3, 29, 18, 343903, tzinfo=utc), null=True, verbose_name='Время аварии'),
        ),
    ]
