# Generated by Django 2.0.3 on 2018-03-30 03:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rd90', '0019_auto_20180330_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rd90calc',
            name='air_t',
            field=models.IntegerField(default=20, verbose_name='Температура воздуха (C)'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='chemicals_amount_calc',
            field=models.CharField(choices=[('tank_substance_amount', 'для одной емкости'), ('full_substance_amount', 'для всего количества вещества')], default='full_substance_amount', max_length=30, verbose_name='Расчет для:'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='crash_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 30, 3, 36, 21, 116260, tzinfo=utc), null=True, verbose_name='Время аварии'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='minutes_after_crach',
            field=models.IntegerField(blank=True, default=60, null=True, verbose_name='Количество минут после аварии'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='wind_speed',
            field=models.IntegerField(default=0, verbose_name='Скорость ветра (м/с)'),
        ),
    ]
