# Generated by Django 2.0.3 on 2018-03-30 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rd90', '0020_auto_20180330_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rd90calc',
            name='chemicals_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geobjects.SubstanceAmount', verbose_name='Количество вещества (т)'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='chemicals_amount_calc',
            field=models.CharField(choices=[('tank_substance_amount', 'для одной емкости на объекте'), ('full_substance_amount', 'для всего количества вещества на объекте'), ('set_substance_amount', 'для указанного количества вещества')], default='full_substance_amount', max_length=30, verbose_name='Расчет для:'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='crash_dtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время аварии'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='hc_storage',
            field=models.CharField(choices=[('liquid', 'жидкость'), ('gas', 'газ')], default='liquid', max_length=8, verbose_name='Хранение АХОВ'),
        ),
    ]
