# Generated by Django 2.0.3 on 2018-03-30 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geobjects', '0011_auto_20180330_0619'),
        ('rd90', '0021_auto_20180330_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='rd90calc',
            name='chemical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geobjects.SubstanceAmount', verbose_name='Количество вещества (т)'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='chemicals_amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество вещества'),
        ),
    ]
