# Generated by Django 2.0.3 on 2018-03-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rd90', '0022_auto_20180330_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='rd90calc',
            name='wind_direction',
            field=models.CharField(blank=True, choices=[('N', 'северный'), ('S', 'южный'), ('E', 'восточный'), ('W', 'западный'), ('NE', 'северо-восточный'), ('NW', 'северо-западный'), ('SW', 'юго-западный'), ('SE', 'юго-восточный')], default='NW', max_length=20, verbose_name='Направление ветра'),
        ),
    ]
