# Generated by Django 2.0.3 on 2018-03-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rd90', '0024_remove_rd90calc_hc_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rd90calc',
            name='hc_storage',
            field=models.CharField(choices=[('liquid', 'жидкость'), ('gas', 'газ')], default='liquid', max_length=8, verbose_name='Хранение АХОВ'),
        ),
    ]
