# Generated by Django 2.0.3 on 2018-04-02 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
        ('rd90', '0025_rd90calc_hc_storage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rd90calc',
            old_name='minutes_after_crach',
            new_name='minutes_after_crash',
        ),
        migrations.RemoveField(
            model_name='rd90calc',
            name='air_t',
        ),
        migrations.RemoveField(
            model_name='rd90calc',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='rd90calc',
            name='dovsoa',
        ),
        migrations.RemoveField(
            model_name='rd90calc',
            name='time_of_day',
        ),
        migrations.RemoveField(
            model_name='rd90calc',
            name='wind_direction',
        ),
        migrations.RemoveField(
            model_name='rd90calc',
            name='wind_speed',
        ),
        migrations.AddField(
            model_name='rd90calc',
            name='actual_contamination_area',
            field=models.FloatField(blank=True, default=0, verbose_name='Площадь зоны фактического заражения АХОВ (квадр. км)'),
        ),
        migrations.AddField(
            model_name='rd90calc',
            name='angular_size',
            field=models.IntegerField(blank=True, default=0, verbose_name='Значение углового размера зоны заражения (град)'),
        ),
        migrations.AddField(
            model_name='rd90calc',
            name='evaporation_duration',
            field=models.DurationField(blank=True, editable=False, verbose_name='Продолжительность испарения вещества'),
        ),
        migrations.AddField(
            model_name='rd90calc',
            name='full_contamination_depth',
            field=models.FloatField(blank=True, default=0, verbose_name='Полная глубина зоны заражения Г (км)'),
        ),
        migrations.AddField(
            model_name='rd90calc',
            name='possible_contamination_area',
            field=models.FloatField(blank=True, default=0, verbose_name='Площадь зоны возможного заражения АХОВ (квадр. км)'),
        ),
        migrations.AddField(
            model_name='rd90calc',
            name='weather',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.Weather', verbose_name='Погодные условия'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='hc_storage',
            field=models.CharField(choices=[('liquid', 'жидкость'), ('gas', 'газ'), ('calc', 'вычисляется')], default='calc', max_length=8, verbose_name='Способ хранение АХОВ'),
        ),
    ]
