# Generated by Django 2.0.3 on 2018-04-02 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rd90', '0026_auto_20180402_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rd90calc',
            name='minutes_after_crash',
        ),
        migrations.AddField(
            model_name='rd90calc',
            name='after_crash_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0, 3600), null=True, verbose_name='Количество минут после аварии'),
        ),
    ]
