# Generated by Django 2.0.3 on 2018-04-03 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rd90', '0030_auto_20180402_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rd90calc',
            name='actual_contamination_area',
            field=models.FloatField(blank=True, default=0, max_length=10000.0, verbose_name='Площадь зоны фактического заражения АХОВ (квадр. км)'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='chem_danger_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geobjects.Object', verbose_name='ХОО'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='chemical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geobjects.SubstanceAmount', verbose_name='Количество вещества (т)'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='chemicals_amount_calc',
            field=models.CharField(choices=[('full', 'всех емкостей'), ('one_tank', 'одной емкости'), ('is_set', 'is_set')], default='full', max_length=10, verbose_name='Расчет для:'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='crash_dtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время аварии'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='full_contamination_depth',
            field=models.FloatField(blank=True, default=0, max_length=500.0, verbose_name='Полная глубина зоны заражения Г (км)'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='possible_contamination_area',
            field=models.FloatField(blank=True, default=0, max_length=10000.0, verbose_name='Площадь зоны возможного заражения АХОВ (квадр. км)'),
        ),
    ]
