# Generated by Django 2.0.3 on 2018-04-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rd90', '0031_auto_20180403_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rd90calc',
            name='actual_contamination_area',
            field=models.FloatField(blank=True, default=0, verbose_name='Площадь зоны фактического заражения АХОВ (квадр. км)'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='angular_size',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Значение углового размера зоны заражения (град)'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='crash_dtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время аварии'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='possible_contamination_area',
            field=models.FloatField(blank=True, default=0, verbose_name='Площадь зоны возможного заражения АХОВ (квадр. км)'),
        ),
    ]
