# Generated by Django 2.0.3 on 2018-04-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rd90', '0032_auto_20180403_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rd90calc',
            name='evaporation_duration',
            field=models.DurationField(blank=True, editable=False, null=True, verbose_name='Продолжительность испарения вещества'),
        ),
    ]
