# Generated by Django 2.0.3 on 2018-04-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rd90', '0033_auto_20180403_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rd90calc',
            name='chemicals_amount_calc',
        ),
    ]
