# Generated by Django 2.0.3 on 2018-04-03 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rd90', '0034_remove_rd90calc_chemicals_amount_calc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rd90calc',
            name='actual_contamination_area',
            field=models.FloatField(blank=True, default=0, editable=False, verbose_name='Площадь зоны фактического заражения АХОВ (квадр. км)'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='angular_size',
            field=models.PositiveSmallIntegerField(blank=True, default=0, editable=False, verbose_name='Значение углового размера зоны заражения (град)'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='full_contamination_depth',
            field=models.FloatField(blank=True, default=0, editable=False, max_length=500.0, verbose_name='Полная глубина зоны заражения Г (км)'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='possible_contamination_area',
            field=models.FloatField(blank=True, default=0, editable=False, verbose_name='Площадь зоны возможного заражения АХОВ (квадр. км)'),
        ),
        migrations.AlterField(
            model_name='rd90calc',
            name='weather',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.Weather', verbose_name='Погодные условия'),
        ),
    ]
