# Generated by Django 2.0.3 on 2018-04-03 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rd90', '0035_auto_20180403_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rd90calc',
            name='chemicals_amount',
        ),
        migrations.RemoveField(
            model_name='rd90calc',
            name='hc_storage',
        ),
    ]
