# Generated by Django 2.0.3 on 2018-04-03 20:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rd90', '0036_auto_20180403_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='rd90calc',
            name='json_calculation',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
    ]
