# Generated by Django 2.1.4 on 2018-12-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регион'},
        ),
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(default='xx', max_length=100),
            preserve_default=False,
        ),
    ]
