# Generated by Django 2.1.4 on 2018-12-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_remove_region_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Идентификатор'),
        ),
    ]
