# Generated by Django 2.1.4 on 2018-12-18 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_region_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='slug',
            new_name='slug_name',
        ),
    ]
