# Generated by Django 2.1.4 on 2018-12-24 21:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0007_auto_20181218_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='region_border',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
