# Generated by Django 2.1.4 on 2018-12-24 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0008_region_region_border'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='region_border',
            new_name='borders',
        ),
    ]
