# Generated by Django 2.1.4 on 2019-01-04 16:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0009_auto_20181225_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='map_center',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='центр карты'),
        ),
    ]
