# Generated by Django 2.0.3 on 2018-04-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(default='Moscow', editable=False, max_length=50, verbose_name='Название города')),
                ('dtime', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Время')),
                ('time_of_day', models.CharField(blank=True, choices=[('morning', 'утро'), ('day', 'день'), ('evening', 'вечер'), ('night', 'ночь'), ('', 'вычисляется')], default='', max_length=50, verbose_name='Время суток')),
                ('wind_speed', models.FloatField(default=0, verbose_name='Скорость ветра (м/с)')),
                ('wind_direction', models.CharField(blank=True, choices=[('N', 'северный'), ('S', 'южный'), ('E', 'восточный'), ('W', 'западный'), ('NE', 'северо-восточный'), ('NW', 'северо-западный'), ('SW', 'юго-западный'), ('SE', 'юго-восточный')], default='NW', max_length=20, verbose_name='Направление ветра')),
                ('air_t', models.IntegerField(default=20, verbose_name='Температура воздуха (C)')),
                ('atmospheric_pressure', models.IntegerField(default=760, verbose_name='Атмосферное давление (мм рт. ст.)')),
                ('dovsoa', models.CharField(blank=True, choices=[('из', 'изотермия'), ('ин', 'инверсия'), ('к', 'конверсия'), ('', 'вычисляется')], default='', max_length=10, verbose_name='Cтепень вертикальной устойчивости воздуха')),
            ],
            options={
                'verbose_name': 'Погодные условия',
                'db_table': 'weather',
                'verbose_name_plural': 'Погодные условия',
            },
        ),
    ]
