# Generated by Django 2.0.3 on 2018-04-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='dovsoa',
            field=models.CharField(blank=True, choices=[('из', 'изотермия'), ('ин', 'инверсия'), ('к', 'конверсия'), ('', 'вычисляется')], default='', max_length=10, null=True, verbose_name='Cтепень вертикальной устойчивости воздуха'),
        ),
    ]
